bugfix: NoClassDefFoundError for "TelephonyCallback"
happened on Android 9 device when SignalSender.start was called
because: TelephonyCallback is not defined in Android 9

refactoring into FiveGDetection seemed to be the simplest fix, and also abstracts away that 5G detection functionality from SignalSender